
import React,{useEffect,useState} from 'react'
import { api } from '../lib/api.js'
export default function Admin(){ const [users,setUsers]=useState([]); const [name,setName]=useState(''); const [teacherEmail,setTeacherEmail]=useState('alice@school.com'); const [schedule,setSchedule]=useState('Mon 10:00-11:30, Wed 10:00-11:30'); const [classId,setClassId]=useState(''); const [studentEmail,setStudentEmail]=useState('s1@school.com');
useEffect(()=>{ load() },[])
async function load(){ try{ const r=await api.adminUsers(); setUsers(r.users) }catch(e){ console.error(e) } }
async function createClass(e){ e.preventDefault(); const sched=schedule.split(',').map(s=>{ const [day,time]=s.trim().split(' '); return {day,time}}); try{ const r=await api.adminCreateClass({name,teacherEmail,schedule:sched}); setClassId(r.class.id); alert('Created '+r.class.id) }catch(e){ alert(e.message) } }
async function enroll(e){ e.preventDefault(); try{ const r=await api.adminEnroll({classId,studentEmail}); alert('Enrolled, now '+r.class.studentEmails.length+' students') }catch(e){ alert(e.message) } }
return (<div><h2>Admin Dashboard</h2><div className="grid"><div className="card"><h3>Create Class</h3><form onSubmit={createClass} className="grid"><input className="input" placeholder="Class name" value={name} onChange={e=>setName(e.target.value)} /><input className="input" placeholder="Teacher email" value={teacherEmail} onChange={e=>setTeacherEmail(e.target.value)} /><input className="input" placeholder="Schedule" value={schedule} onChange={e=>setSchedule(e.target.value)} /><button className="btn">Create</button></form></div><div className="card"><h3>Enroll Student</h3><form onSubmit={enroll} className="grid"><input className="input" placeholder="Class ID" value={classId} onChange={e=>setClassId(e.target.value)} /><input className="input" placeholder="Student email" value={studentEmail} onChange={e=>setStudentEmail(e.target.value)} /><button className="btn">Enroll</button></form></div></div><div className="card"><h3>All Users</h3><ul className="list">{users.map(u=> <li key={u.id}>{u.name} — {u.email} <span className="badge">{u.role}</span></li>)}</ul></div></div>) }
