
import React,{useEffect,useState} from 'react'
import { api } from '../lib/api.js'
import { io } from 'socket.io-client'
const socket = io('http://localhost:4000')
export default function Student(){ const [classes,setClasses]=useState([]); const [selected,setSelected]=useState(null); const [homeworks,setHomeworks]=useState([]); const [file,setFile]=useState(null); const [text,setText]=useState(''); const [badges,setBadges]=useState([]); const [streak,setStreak]=useState(0); const [notices,setNotices]=useState([]); const [msgs,setMsgs]=useState([]); const [chatText,setChatText]=useState('');
useEffect(()=>{ load(); const s=socket; s.on('notice:new',n=> setNotices(prev=>[n,...prev])); s.on('homework:new',hw=> setHomeworks(prev=>[hw,...prev])); return ()=>{ s.off('notice:new'); s.off('homework:new') } },[])
async function load(){ const c=await api.studentClasses(); setClasses(c.classes); const b=await api.badges(); setBadges(b.badges); setStreak(b.streak); const n=await api.notices(); setNotices(n.notices) }
useEffect(()=>{ if(selected){ socket.emit('chat:join',{room:selected.id,user:'Student'}); socket.on('chat:message',m=> setMsgs(prev=>[m,...prev])); socket.on('chat:system',m=> setMsgs(prev=>[m,...prev])); api.classHomework(selected.id).then(r=> setHomeworks(r.homeworks)); return ()=>{ socket.off('chat:message'); socket.off('chat:system') } } },[selected])
async function submit(hw){ await api.submitHomework(selected.id,hw.id,text,file); alert('Submitted'); setText(''); setFile(null) }
function sendChat(){ socket.emit('chat:message',{room:selected.id,text:chatText}); setChatText('') }
return (<div><h2>Student Dashboard</h2><div className="row"><div className="card" style={{flex:1}}><h3>Your Classes</h3><ul className="list">{classes.map(c=> <li key={c.id} onClick={()=>setSelected(c)} style={{cursor:'pointer'}}><b>{c.name}</b> — {c.schedule.map(s=>`${s.day} ${s.time}`).join(', ')}</li>)}</ul></div><div className="card" style={{flex:2}}>{selected? (<div><h3>{selected.name}</h3><h4>Homework</h4><ul className="list">{homeworks.map(hw=> <li key={hw.id}><b>{hw.title}</b> — due {hw.dueDate}<br/><small>{hw.description}</small><div className="row"><input className="input" placeholder="Notes" value={text} onChange={e=>setText(e.target.value)} /><input className="input" type="file" onChange={e=>setFile(e.target.files[0])} /><button className="btn" onClick={()=>submit(hw)}>Upload</button></div></li>)}</ul></div>) : <p>Select a class.</p>}</div><div className="card" style={{flex:1}}><h3>Your Badges</h3><p>Streak: <b>{streak}</b> days</p>{badges.map(b=> <span key={b} className="badge">{b}</span>)}<h3 style={{marginTop:12}}>Notices</h3><ul className="list">{notices.map(n=> <li key={n.id}><b>{n.title}</b><br/><small>{new Date(n.createdAt).toLocaleString()}</small><div>{n.text}</div></li>)}</ul></div></div>{selected && (<div className="card"><h3>Class Chat</h3><div style={{maxHeight:240,overflow:'auto'}}>{msgs.map((m,i)=> <div key={i}><small>{new Date(m.ts).toLocaleTimeString()}</small> — {m.user}: {m.text}</div>)}</div><div className="row"><input className="input" value={chatText} onChange={e=>setChatText(e.target.value)} /><button className="btn" onClick={sendChat}>Send</button></div></div>)}</div>) }
