
import React,{useEffect,useState} from 'react'
import { api } from '../lib/api.js'
import { io } from 'socket.io-client'
const socket = io('http://localhost:4000')
export default function Teacher(){ const [classes,setClasses]=useState([]); const [selected,setSelected]=useState(null); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [present,setPresent]=useState([]); const [title,setTitle]=useState(''); const [desc,setDesc]=useState(''); const [due,setDue]=useState(''); const [noticeTitle,setNoticeTitle]=useState(''); const [noticeText,setNoticeText]=useState(''); const [msgs,setMsgs]=useState([]); const [chatText,setChatText]=useState('');
useEffect(()=>{ load() },[])
useEffect(()=>{ if(selected){ socket.emit('chat:join',{room:selected.id,user:'Teacher'}) ; socket.on('chat:message',m=> setMsgs(prev=>[m,...prev])); socket.on('chat:system',m=> setMsgs(prev=>[m,...prev])); return ()=>{ socket.off('chat:message'); socket.off('chat:system') } } },[selected])
async function load(){ const r=await api.teacherClasses(); setClasses(r.classes) }
async function takeAttendance(){ if(!selected) return; await api.takeAttendance(selected.id,date,present); alert('Saved') }
async function postHW(){ if(!selected) return; await api.createHomework(selected.id,{title,description:desc,dueDate:due}); alert('Posted') }
async function sendNotice(){ await api.createNotice(noticeTitle,noticeText); alert('Sent') }
function toggle(email){ setPresent(p=> p.includes(email)? p.filter(x=>x!==email): [...p,email]) }
function sendChat(){ socket.emit('chat:message',{room:selected.id,text:chatText}); setChatText('') }
return (<div><h2>Teacher Dashboard</h2><div className="row"><div className="card" style={{flex:1}}><h3>Your Classes</h3><ul className="list">{classes.map(c=> <li key={c.id} onClick={()=>setSelected(c)} style={{cursor:'pointer'}}><b>{c.name}</b> — {c.schedule.map(s=>`${s.day} ${s.time}`).join(', ')}</li>)}</ul></div><div className="card" style={{flex:2}}>{selected? (<div><h3>{selected.name}</h3><div className="grid"><div className="card"><h4>Attendance</h4><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)} /><div>{selected.studentEmails.map(email=> <label key={email} style={{display:'block'}}><input type="checkbox" checked={present.includes(email)} onChange={()=>toggle(email)} /> {email}</label>)}</div><button className="btn" onClick={takeAttendance}>Save Attendance</button></div><div className="card"><h4>Post Homework</h4><input className="input" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)} /><input className="input" placeholder="Due YYYY-MM-DD" value={due} onChange={e=>setDue(e.target.value)} /><textarea className="input" rows="4" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)}></textarea><button className="btn" onClick={postHW}>Publish</button></div></div></div>) : <p>Select a class.</p>}</div><div className="card" style={{flex:1}}><h3>Notices</h3><input className="input" placeholder="Title" value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)} /><textarea className="input" rows="3" placeholder="Text" value={noticeText} onChange={e=>setNoticeText(e.target.value)}></textarea><button className="btn" onClick={sendNotice}>Send</button></div></div>{selected && (<div className="card"><h3>Class Chat</h3><div style={{maxHeight:240,overflow:'auto'}}>{msgs.map((m,i)=> <div key={i}><small>{new Date(m.ts).toLocaleTimeString()}</small> — {m.user}: {m.text}</div>)}</div><div className="row"><input className="input" value={chatText} onChange={e=>setChatText(e.target.value)} /><button className="btn" onClick={sendChat}>Send</button></div></div>)}</div>) }
